### ISSUE TITLE
Fatal if global themes directories don't exist

### ISSUE THREAD

**Issue by emodric** [lolautruche/EzCoreExtraBundle#20]
After upgrading to version 0.6.1, I get the following exception:

```                            
  [InvalidArgumentException]                                                   
  The "/var/www/html/netgensite/app/Resources/views/themes" directory does not exist.                                       
```

Also applies to global assets directory (`web/assets/themes`).

This looks like it is related to a fix available in version 0.6.1 of the bundle.

**Comment by lolautruche** [comment]
Yes indeed, thanks. It was reported by several people.
Gonna fix this right away :-)
