### ISSUE TITLE
Theme support twig / asset files

### ISSUE THREAD

**Issue by fwoldt** [lolautruche/EzCoreExtraBundle#4]
The imlementet theme solution looks interesting - but if you want to use the themes feature you have to use '@ezdesign' in your bundles for ez override templates.

The Bundle https://github.com/liip/LiipThemeBundle can override every twig template! It defines Fallbackthemes like yours, too. But you do not need to use a special syntax to load a twig template.

This is a very big advantage - so you can use any symfony bundle with custom controllers an can override the templates in your new custom theme!!!! You can override every twig template without modify the src code!!!!

If you use TemplateOverriding for every TwigTemplate a new Setting with bundles which include theme templates would be fine to minimize the filesystem calls:

For asset overriding you could do the same. You could override every asset called with the tpl command in a loaded twig template e.g. asset( 'bundles/ezdemo/images/logo-ez.png' ) by scanning all themes asset bundles. I had send you an E-Mail with my example Implementation of asset overriding for Ideas.
I would place the assets under
myBundle/Resources/public/themes/ mytheme/ images | css | js

It would be great to have a solution where you can use 1 2 3 4 5 3rd party bundles and customize all available views by overrding the templates and assets by SITEACCESS. So you can setup a real multisitesetup 1 Database with different Designs - how we can do easily in ezpublish 4

**Comment by lolautruche** [comment]
Thanks @fwoldt !

I'll see what can be done for that.

**Comment by htollefsen** [comment]
This really would have been a great feature!

**Comment by lolautruche** [comment]
I'll see what I can do, but first things first 😉 . I'm currently working on assets support.

**Comment by lolautruche** [comment]
@htollefsen @fwoldt You can now add *additional theme paths* when using EzPlatformDesignEngine. You may add any views directory to a theme by configuration.

https://github.com/ezsystems/ezplatform-design-engine/blob/master/doc/templates.md#additional-theme-paths

Hence I'm gonna close this issue.
