### ISSUE TITLE
getContent() instead of getLocation()

### ISSUE THREAD

**Issue by flutchman** [lolautruche/EzCoreExtraBundle#40]
https://github.com/lolautruche/EzCoreExtraBundle/blob/8f172ac4273ffd74dd869bfe56fda64739ba32d6/View/ConfigurableView.php#L177

On getLocation() function, we should have a location instead of a content in return.

Regards,

**Comment by lolautruche** [comment]
Fixed in aa32472

**Comment by lolautruche** [comment]
Thanks @flutchman !
